name: wbdg
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  smooth_page_indicator: any
  google_nav_bar: 5.0.6
  firebase_core: 2.3.0
  firebase_auth: 4.1.3
  cloud_firestore: 4.1.0
  firebase_database: 10.0.6
  carousel_slider: 4.1.1
  get: 4.6.5
  firebase_storage: 11.0.6
  line_icons: 2.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/font/Poppins-Regular.ttf
  assets: 
    - assets/images/logowbputih.png
    - assets/images/intro2.png
    - assets/images/intro3.png
  uses-material-design: true

